// <auto-generated />
using Aguacongas.AspNetCore.Authentication.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Thor.SSO.Migrations.SchemeDb
{
    [DbContext(typeof(SchemeDbContext))]
    [Migration("20201220132919_DynamicAuthenticationStore")]
    partial class DynamicAuthenticationStore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Aguacongas.AspNetCore.Authentication.EntityFramework.SchemeDefinition", b =>
                {
                    b.Property<string>("Scheme")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedHandlerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerializedOptions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Scheme");

                    b.ToTable("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
